import React, { useState } from "react";
import { FileText, Download, Code2, Copy, X } from "lucide-react";
import useAppStore from "../../store/useAppStore";
import { generateAllSnippets } from "../../utils/codeGenerator";
import "./DocsGenerator.css";

function DocsGenerator({ collection, onClose }) {
  const [copiedIndex, setCopiedIndex] = useState(null);

  if (!collection) return null;

  const handleCopy = (text, index) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const handleExportMarkdown = () => {
    let md = `# API Documentation: ${collection.name}\n\n`;
    md += `Generated by APIForge\n\n---\n\n`;

    collection.requests.forEach((req, idx) => {
      md += `## ${idx + 1}. ${req.method} ${req.url}\n\n`;
      
      if (req.headers && req.headers.length > 0) {
        md += `### Headers\n`;
        md += `| Key | Value |\n|---|---|\n`;
        req.headers.forEach((h) => {
          if (h.enabled && h.key) md += `| \`${h.key}\` | \`${h.value}\` |\n`;
        });
        md += `\n`;
      }

      if (req.body) {
        md += `### Request Body\n\`\`\`json\n${req.body}\n\`\`\`\n\n`;
      }
      
      const snippets = generateAllSnippets({
        method: req.method,
        url: req.url,
        headers: req.headers?.reduce((acc, h) => {
          if (h.enabled && h.key) acc[h.key] = h.value;
          return acc;
        }, {}) || {},
        body: req.body,
      });

      md += `### Example cURL\n\`\`\`bash\n${snippets.curl}\n\`\`\`\n\n`;
      md += `---\n\n`;
    });

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${collection.name.replace(/\s+/g, "_")}_Docs.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="docs-overlay">
      <div className="docs-modal">
        <div className="docs-header">
          <div className="docs-header-left">
            <FileText size={20} className="docs-icon" />
            <div>
              <h2 className="docs-title">{collection.name}</h2>
              <span className="docs-subtitle">API Documentation</span>
            </div>
          </div>
          <div className="docs-header-right">
            <button className="docs-action-btn" onClick={handleExportMarkdown}>
              <Download size={16} /> Export MD
            </button>
            <button className="docs-close-btn" onClick={onClose}>
              <X size={20} />
            </button>
          </div>
        </div>

        <div className="docs-content">
          {collection.requests.length === 0 ? (
            <div className="docs-empty">
              This collection has no requests yet.
            </div>
          ) : (
            collection.requests.map((req, index) => {
              const snippets = generateAllSnippets({
                method: req.method,
                url: req.url,
                headers: req.headers?.reduce((acc, h) => {
                  if (h.enabled && h.key) acc[h.key] = h.value;
                  return acc;
                }, {}) || {},
                body: req.body,
              });

              return (
                <div key={req.id} className="docs-endpoint">
                  <div className="docs-endpoint-header">
                    <span className={`docs-method method-${req.method.toLowerCase()}`}>
                      {req.method}
                    </span>
                    <span className="docs-url">{req.url}</span>
                  </div>

                  <div className="docs-endpoint-body">
                    <div className="docs-left">
                      {/* Headers */}
                      {req.headers && req.headers.some((h) => h.enabled && h.key) && (
                        <div className="docs-section">
                          <h4 className="docs-section-title">Headers</h4>
                          <table className="docs-table">
                            <thead>
                              <tr>
                                <th>Key</th>
                                <th>Value</th>
                              </tr>
                            </thead>
                            <tbody>
                              {req.headers.map(
                                (h, i) =>
                                  h.enabled &&
                                  h.key && (
                                    <tr key={i}>
                                      <td className="docs-code">{h.key}</td>
                                      <td>{h.value}</td>
                                    </tr>
                                  )
                              )}
                            </tbody>
                          </table>
                        </div>
                      )}

                      {/* Request Body */}
                      {req.body && (
                        <div className="docs-section">
                          <h4 className="docs-section-title">Request Body</h4>
                          <pre className="docs-code-block">{req.body}</pre>
                        </div>
                      )}
                    </div>

                    <div className="docs-right">
                      <div className="docs-section">
                        <div className="docs-section-header">
                          <h4 className="docs-section-title">Example Request</h4>
                          <button
                            className="docs-copy-btn"
                            onClick={() => handleCopy(snippets.curl, index)}
                          >
                            {copiedIndex === index ? "Copied" : <><Copy size={12} /> Copy</>}
                          </button>
                        </div>
                        <pre className="docs-code-block dark">{snippets.curl}</pre>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })
          )}
        </div>
      </div>
    </div>
  );
}

export default DocsGenerator;
